// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /github-connection"
  | "DELETE /watched-repositories/{repositoryId}"
  | "GET /chat-destination"
  | "GET /github-connection"
  | "GET /notifications"
  | "GET /watched-repositories"
  | "POST /github-connection"
  | "POST /watched-repositories"
  | "PUT /chat-destination";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /github-connection": { kind: "scope", scope: "github-connection:manage" },
  "DELETE /watched-repositories/{repositoryId}": { kind: "scope", scope: "watched-repositories:manage" },
  "GET /chat-destination": { kind: "scope", scope: "chat-destination:read" },
  "GET /github-connection": { kind: "scope", scope: "github-connection:read" },
  "GET /notifications": { kind: "scope", scope: "notifications:read" },
  "GET /watched-repositories": { kind: "scope", scope: "watched-repositories:read" },
  "POST /github-connection": { kind: "scope", scope: "github-connection:manage" },
  "POST /watched-repositories": { kind: "scope", scope: "watched-repositories:manage" },
  "PUT /chat-destination": { kind: "scope", scope: "chat-destination:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
