// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "chat-destination:manage"
  | "chat-destination:read"
  | "github-connection:manage"
  | "github-connection:read"
  | "notifications:read"
  | "watched-repositories:manage"
  | "watched-repositories:read";

export type Role =
  | "Administrator";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["chat-destination:manage", "chat-destination:read", "github-connection:manage", "github-connection:read", "notifications:read", "watched-repositories:manage", "watched-repositories:read"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Administrator"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Administrator": ["chat-destination:manage", "chat-destination:read", "github-connection:manage", "github-connection:read", "notifications:read", "watched-repositories:manage", "watched-repositories:read"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Administrator": ["SyncAdmins"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Administrator": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
