// Generated by `bal openapi --mode service` from
// specs/design/components/github-sync-api/openapi.yaml, then filled in.
// Every resource requires a signed-in Administrator (see
// service_helpers.bal's `authenticate`) — this contract declares no
// `security: []` operation.
import ballerina/http;
import ballerina/time;
import ballerina/uuid;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's GitHub connection status
    resource function get github\-connection(http:RequestContext ctx) returns GithubConnection|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        GithubConnectionRow? row = check getGithubConnectionRow();
        if row is () {
            return {connected: false};
        }
        return {
            connected: true,
            githubUsername: row.githubUsername,
            connectedAt: toRfc3339(row.connectedAt)
        };
    }

    # Complete GitHub OAuth authorization and store the connection
    resource function post github\-connection(http:RequestContext ctx, @http:Payload githubconnection_body payload)
            returns http:Created|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        string|error accessToken = exchangeGithubCode(payload.code);
        if accessToken is error {
            return <ErrorBadRequest>{body: {code: 400, message: "The authorization code was invalid or expired"}};
        }
        string? githubUsername = fetchGithubUsername(accessToken);
        time:Utc connectedAt = time:utcNow();
        check upsertGithubConnection(caller.userId, githubUsername, accessToken, connectedAt);
        GithubConnection connection = {
            connected: true,
            githubUsername: githubUsername,
            connectedAt: toRfc3339(connectedAt)
        };
        return <http:Created>{body: connection};
    }

    # Disconnect the authorized GitHub account
    resource function delete github\-connection(http:RequestContext ctx) returns http:NoContent|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        check deleteGithubConnectionRow();
        return http:NO_CONTENT;
    }

    # Every watched repository
    resource function get watched\-repositories(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        int effectiveLimit = 'limit > 100 ? 100 : 'limit;
        [WatchedRepositoryRow[], int] queryResult = check listWatchedRepositories(effectiveLimit, offset);
        WatchedRepositoryRow[] rows = queryResult[0];
        int total = queryResult[1];
        WatchedRepository[] data = from WatchedRepositoryRow row in rows select toWatchedRepository(row);
        [string?, string?] links = paginationLinks("/watched-repositories", effectiveLimit, offset, total);
        return {count: total, next: links[0], previous: links[1], data: data};
    }

    # Add a repository to the watch list
    resource function post watched\-repositories(http:RequestContext ctx, @http:Payload watchedrepositories_body payload)
            returns http:Created|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        WatchedRepositoryRow? existing = check findWatchedRepositoryByOwnerName(payload.owner, payload.name);
        if existing is WatchedRepositoryRow {
            return <ErrorBadRequest>{body: {code: 400, message: "This repository is already watched"}};
        }
        time:Utc addedAt = time:utcNow();
        WatchedRepositoryRow row = {id: uuid:createRandomUuid(), owner: payload.owner, name: payload.name, addedAt: addedAt};
        check insertWatchedRepository(row);
        return <http:Created>{body: toWatchedRepository(row)};
    }

    # Remove a repository from the watch list
    resource function delete watched\-repositories/[string repositoryId](http:RequestContext ctx)
            returns http:NoContent|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        boolean removed = check deleteWatchedRepositoryById(repositoryId);
        if !removed {
            return <ErrorNotFound>{body: {code: 404, message: "No watched repository with this id"}};
        }
        return http:NO_CONTENT;
    }

    # The configured Google Chat destination
    resource function get chat\-destination(http:RequestContext ctx) returns ChatDestination|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        ChatDestinationRow? row = check getChatDestinationRow();
        if row is () {
            return {spaceName: (), webhookUrl: (), updatedAt: ()};
        }
        return {spaceName: row.spaceName, webhookUrl: row.webhookUrl, updatedAt: toRfc3339(row.updatedAt)};
    }

    # Set the Google Chat space notifications are posted to
    resource function put chat\-destination(http:RequestContext ctx, @http:Payload chatdestination_body payload)
            returns ChatDestination|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        if !isWellFormedAbsoluteUrl(payload.webhookUrl) {
            return <ErrorBadRequest>{body: {code: 400, message: "The webhook URL is not a valid absolute URL"}};
        }
        time:Utc updatedAt = time:utcNow();
        check upsertChatDestination(payload.spaceName, payload.webhookUrl, updatedAt);
        return {spaceName: payload.spaceName, webhookUrl: payload.webhookUrl, updatedAt: toRfc3339(updatedAt)};
    }

    # The log of notifications sent, most recent first
    resource function get notifications(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200_1|ErrorUnauthorized|error {
        GatewayCaller|ErrorUnauthorized caller = authenticate(ctx);
        if caller !is GatewayCaller {
            return caller;
        }
        int effectiveLimit = 'limit > 100 ? 100 : 'limit;
        [NotificationRow[], int] queryResult = check listNotifications(effectiveLimit, offset);
        NotificationRow[] rows = queryResult[0];
        int total = queryResult[1];
        Notification[] data = from NotificationRow row in rows select toNotification(row);
        [string?, string?] links = paginationLinks("/notifications", effectiveLimit, offset, total);
        return {count: total, next: links[0], previous: links[1], data: data};
    }
}

function toWatchedRepository(WatchedRepositoryRow row) returns WatchedRepository {
    string addedAt = toRfc3339(row.addedAt) ?: "";
    return {id: row.id, owner: row.owner, name: row.name, addedAt: addedAt};
}

function toNotification(NotificationRow row) returns Notification {
    "sent"|"failed" status = row.status == "sent" ? "sent" : "failed";
    string sentAt = toRfc3339(row.sentAt) ?: "";
    return {
        id: row.id,
        repositoryFullName: row.repositoryFullName,
        issueTitle: row.issueTitle,
        issueUrl: row.issueUrl,
        sentAt: sentAt,
        status: status
    };
}

# Whether a candidate webhook URL is a well-formed absolute http(s) URL —
# PUT /chat-destination's own validation rule (reject e.g. "not-a-url").
#
# + candidate - the value the Administrator submitted
# + return - true when it is an absolute http/https URL with a host
function isWellFormedAbsoluteUrl(string candidate) returns boolean {
    string:RegExp pattern = re `^https?://[^\s/?#]+([/?#].*)?$`;
    return pattern.isFullMatch(candidate);
}

public type GithubConnection record {
    boolean connected?;
    string? githubUsername?;
    string? connectedAt?;
};

public type WatchedRepository record {
    string id?;
    string owner?;
    string name?;
    string addedAt?;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ChatDestination record {
    string? spaceName?;
    string? webhookUrl?;
    string? updatedAt?;
};

public type Notification record {
    string id?;
    string repositoryFullName?;
    string issueTitle?;
    string issueUrl?;
    string sentAt?;
    "sent"|"failed" status?;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type githubconnection_body record {
    # The OAuth authorization code returned by GitHub
    string code;
};

public type chatdestination_body record {
    string spaceName;
    string webhookUrl;
};

public type inline_response_200_1 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Notification[] data;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    WatchedRepository[] data;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};

public type watchedrepositories_body record {
    string owner;
    string name;
};
